apiVersion: v1
kind: Service
metadata:
  name: frontend-loadbalance-service
spec:
  selector:
    type: frontend
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 30800
  type: LoadBalancer
