apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-dp
  labels:
    app: frontend-app
    type: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      type: frontend
  template:
    metadata:
      name: frontend-dp
      labels:
        app: frontend-app
        type: frontend
    spec:
      containers:
        - name: frontend-container
          image: nginx:1.19.4
