apiVersion: v1
kind: Service
metadata:
  labels:
    app: redis
  name: redis
  namespace: vote
spec:
  type: ClusterIP
  ports:
    - port: 6379
      targetPort: 6379
      name: redis-service
  selector:
    app: redis